[build]
  command = "next build"
  publish = "out" # The output directory created by next export

[[plugins]]
  package = "@netlify/plugin-nextjs" # Required for Next.js support on Netlify

[[redirects]]
  from = "/api/files/*"
  to = "api/files/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/posts/*"
  to = "api/posts/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/comments/*"
  to = "api/comments/:splat"
  status = 200
  force = true

[functions]
  directory = ".netlify/functions"
  
