[build]
  command = "next build"


[[plugins]]
  package = "@netlify/plugin-nextjs" # Required for Next.js support on Netlify

[[redirects]]
  from = "/api/*"
  to = "/api/*"
  status = 200
  force = true

[functions]
  edge_handlers = "true"

  [context.production]
  publish = "output/"
  command = "make publish"

