[build]
  # Command to build the Next.js project
  command = "next build && next export"
  
  # The directory to publish from after building
  publish = "out" # Directory created by next export

[[plugins]]
  # The Netlify plugin for Next.js
  package = "@netlify/plugin-nextjs" # This plugin ensures proper Next.js functionality on Netlify


# Optional: Add redirects if necessary
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

  [functions]
  directory = "out/_next/static/functions"
