[build]
  command = "next build"
  publish = "out" # The output directory created by next export

[[plugins]]
  package = "@netlify/plugin-nextjs" # Required for Next.js support on Netlify

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/posts"
  to = "/.netlify/functions/api/posts/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/comments?postId="
  to = "/.netlify/functions/api/comments/:splat"
  status = 200
  force = true

[functions]
  directory = ".netlify/functions"
  
