[build]
  command = "next build"
  publish = "out" # The output directory created by next export

[[plugins]]
  package = "@netlify/plugin-nextjs" # Required for Next.js support on Netlify

[[redirects]]
  from = "/api/files"
  to = "api/:splat"
  from="/api/posts"
  to="api/:splat"
  from="/api/comments"
  to="api/:splat"
  status = 200
  force = true

[functions]
  directory = ".netlify/functions"
  
