[build]
  command = "env && npm run build"
  publish = ".next"

[functions]
  directory = "src/app/netlify/functions"

[[redirects]]
  from = "/api/askai"
  to = "/.netlify/functions/askai"
  status = 200

[[redirects]]
from = "/api/posts"
to  = "/.netlify/functions/posts"
status  = 200

[[redirects]]
from = "/api/comments"
to  = "/.netlify/functions/comments"
status  = 200