[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/askai"
  to = "/.netlify/functions/askai"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"
